spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_postgres
    username: postgres
    password: 111111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 8000  # 根据您要连接的 Redis 实例调整端口
    # 如果 Redis 没有密码，不要设置 password

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework: DEBUG
    com.yourpackage: DEBUG

server:
  port: 8081

sms:
  code:
    expire-time: 10m
    send-frequency: 1m
    send-maximum-per-day: 10
    begin-code: 1000
    end-code: 9999
    redis:
      host: localhost
      port: 8000  # 与上面的 Redis 配置一致
      # 如果没有密码，不要设置 password
      timeout: 6000

application:
  name: linkCutter